name: deploy-main-to-gcp.yml

on:
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to GCP via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e

            cd /home/unokiss307/midterm-exam
            
            git pull origin main

            cd /home/unokiss307/midterm-exam || { echo "Directory not found"; exit 1; }
            
            git pull origin dev
            
            rm -rf node_modules

            npm install --production --no-audit --no-fund

            # Restart app
            pm2 delete "${{ vars.PM2_NAME }}" || true
            pm2 start -f app.mjs --name "${{ vars.PM2_NAME }}"
            pm2 save
            
            echo "successfull deployed!"
