name: Deploy to GCP on Pull Request to Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to GCP via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e

            cd /home/unokiss307 || { echo "Directory not found"; exit 1; }

            rm -rf midterm-exam

            # Clone the repository
            git clone -b dev git@github.com:Kise1205/midterm-exam.git midterm-exam

            cd midterm-exam

            npm ci

            # Restart app
            pm2 delete "${{ vars.PM2_NAME }}" || true
            pm2 start -f app.mjs --name "${{ vars.PM2_NAME }}"
            pm2 save
            
            echo "successfully deployed!"
